modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="grimmscraft"
version="1.0.6"
displayName="G.M.C."
credits="tyuXX"
displayURL="https://www.curseforge.com/minecraft/mc-mods/grimms-craft"
logoFile="logo.png"
authors="tyuXX"
description="Long live C.O.D."

[[dependencies.grimmscraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




